# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
