# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='deneme'),
        ),
    ]
