# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.CharField(default='deneme', max_length=250, verbose_name='Short Content'),
            preserve_default=False,
        ),
    ]
