# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
