# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='deneme', max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
